/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._web_22dinf._pages._tms._route;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.lpmas.framework.web.ParamKit;
import java.util.*;
import com.lpmas.framework.config.*;
import com.lpmas.framework.bean.StatusBean;
import com.lpmas.admin.bean.*;
import com.lpmas.constant.info.*;
import com.lpmas.admin.business.*;
import com.lpmas.tms.route.bean.*;
import com.lpmas.tms.route.config.*;
import com.lpmas.tms.route.business.*;
import com.lpmas.framework.util.*;
import com.lpmas.tms.config.*;

public class _routeinfomanage__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
     
	RouteInfoBean bean = (RouteInfoBean)request.getAttribute("RouteInfo");
	AdminUserHelper adminUserHelper = (AdminUserHelper)request.getAttribute("AdminUserHelper");
	String readOnly = ParamKit.getParameter(request, "readOnly","false").trim();
	Boolean isModifyAble = readOnly.equalsIgnoreCase("true")? false:true;
	request.setAttribute("readOnly", readOnly);
	StationInfoMediator mediator = new StationInfoMediator();

    out.write(_jsp_string1, 0, _jsp_string1.length);
    
String DOMAIN = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "DEFAULT_DOMAIN");
String STATIC_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "STATIC_URL");
String SRM_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "SRM_URL");
String ERP_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "ERP_URL");
String TMS_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "TMS_URL");
String REGION_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "REGION_URL");

    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((DOMAIN));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((bean.getRouteId() ));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((bean.getRouteName() ));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    for(StatusBean<Integer, String> statusBean : RouteConfig.SOURCE_INFO_TYPE_LIST){ 
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((statusBean.getStatus() ));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print(((statusBean.getStatus() == bean.getSourceInfoType())?"selected":"" ));
    out.write('>');
    out.print((statusBean.getValue() ));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    } 
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((mediator.getStationNameByKey(bean.getSourceInfoType(), bean.getSourceInfoId()) ));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((bean.getSourceInfoId()));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    if(isModifyAble){ 
    out.write(_jsp_string18, 0, _jsp_string18.length);
    } 
    out.write(_jsp_string19, 0, _jsp_string19.length);
    for(StatusBean<Integer, String> statusBean : RouteConfig.DESTINATION_INFO_TYPE_LIST){ 
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((statusBean.getStatus() ));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print(((statusBean.getStatus() == bean.getDestinationInfoType())?"selected":"" ));
    out.write('>');
    out.print((statusBean.getValue() ));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    } 
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((mediator.getStationNameByKey(bean.getDestinationInfoType(), bean.getDestinationInfoId()) ));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((bean.getDestinationInfoId()));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    if(isModifyAble){ 
    out.write(_jsp_string22, 0, _jsp_string22.length);
    } 
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((Constants.STATUS_VALID ));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print(((bean.getStatus()==Constants.STATUS_VALID)?"checked":"" ));
    out.write(_jsp_string24, 0, _jsp_string24.length);
    out.print((bean.getMemo() ));
    out.write(_jsp_string25, 0, _jsp_string25.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((InfoTypeConfig.INFO_TYPE_SUPPLIER_ADDRESS));
    out.write(_jsp_string27, 0, _jsp_string27.length);
    out.print((SRM_URL));
    out.write(_jsp_string28, 0, _jsp_string28.length);
    out.print((InfoTypeConfig.INFO_TYPE_WAREHOUSE));
    out.write(_jsp_string27, 0, _jsp_string27.length);
    out.print((ERP_URL));
    out.write(_jsp_string29, 0, _jsp_string29.length);
    out.print((InfoTypeConfig.INFO_TYPE_SUPPLIER_ADDRESS));
    out.write(_jsp_string30, 0, _jsp_string30.length);
    out.print((SRM_URL));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((InfoTypeConfig.INFO_TYPE_WAREHOUSE));
    out.write(_jsp_string30, 0, _jsp_string30.length);
    out.print((ERP_URL));
    out.write(_jsp_string32, 0, _jsp_string32.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/tms/route/RouteInfoManage.jsp"), -2217762756867999999L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/include/header.jsp"), -5467580586608798099L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${readOnly}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;

  private final static char []_jsp_string7;
  private final static char []_jsp_string21;
  private final static char []_jsp_string3;
  private final static char []_jsp_string15;
  private final static char []_jsp_string25;
  private final static char []_jsp_string13;
  private final static char []_jsp_string5;
  private final static char []_jsp_string20;
  private final static char []_jsp_string22;
  private final static char []_jsp_string10;
  private final static char []_jsp_string32;
  private final static char []_jsp_string30;
  private final static char []_jsp_string9;
  private final static char []_jsp_string16;
  private final static char []_jsp_string6;
  private final static char []_jsp_string19;
  private final static char []_jsp_string31;
  private final static char []_jsp_string17;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string27;
  private final static char []_jsp_string28;
  private final static char []_jsp_string23;
  private final static char []_jsp_string11;
  private final static char []_jsp_string2;
  private final static char []_jsp_string12;
  private final static char []_jsp_string24;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string18;
  private final static char []_jsp_string14;
  private final static char []_jsp_string26;
  private final static char []_jsp_string29;
  static {
    _jsp_string7 = "/js/fancyBox/jquery.fancybox.js\"></script>\r\n	<link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string21 = "\"  readOnly size=\"50\" checkStr=\"\u8d77\u70b9\u7ad9;txt;true;;200\"/>\r\n	      	<input type=\"hidden\" name=\"destinationInfoId\" id=\"destinationInfoId\" value=\"".toCharArray();
    _jsp_string3 = "/css/main.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string15 = "\r\n	      	</select>\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\"><span>*</span>\u8d77\u70b9\u7ad9\uff1a</em>\r\n	  		<input type=\"text\" name=\"sourceInfoName\" id=\"sourceInfoName\" value=\"".toCharArray();
    _jsp_string25 = "</textarea>\r\n	    </p>\r\n	  </div>\r\n	  <div class=\"div_center\">\r\n	  <input type=\"submit\" name=\"submit\" id=\"submit\" class=\"modifysubbtn\" value=\"\u63d0\u4ea4\" />\r\n	  <input type=\"button\" name=\"cancel\" id=\"cancel\" value=\"\u53d6\u6d88\" onclick=\"javascript:history.back()\">\r\n	  </div>\r\n	</form>\r\n</body>\r\n<script>\r\n$(document).ready(function() {\r\n	var readOnly = '".toCharArray();
    _jsp_string13 = "\" ".toCharArray();
    _jsp_string5 = "/js/common.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string20 = "\r\n	      	</select>\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\"><span>*</span>\u7ec8\u70b9\u7ad9\uff1a</em>\r\n	  		<input type=\"text\" name=\"destinationInfoName\" id=\"destinationInfoName\" value=\"".toCharArray();
    _jsp_string22 = "\r\n	      	<input type=\"button\" name=\"selectDestinationInfo\" id=\"selectDestinationInfo\" value=\"\u6dfb\u52a0\" />\r\n	      	".toCharArray();
    _jsp_string10 = "\"/>\r\n	  <div class=\"modify_form\">\r\n	    <p>\r\n	      <em class=\"int_label\"><span>*</span>\u8def\u5f84\u540d\u79f0\uff1a</em>\r\n	      <input type=\"text\" name=\"routeName\" id=\"routeName\" size=\"50\" maxlength=\"100\" value=\"".toCharArray();
    _jsp_string32 = "/erp/WarehouseInfoSelect.do?callbackFun=selectWarehouse&echoParameter=destinationInfo&warehouseId=\"+ destinationInfoId;\r\n			}\r\n			$.fancybox.open({\r\n				href : url,\r\n				type : 'iframe',\r\n				width : 760,\r\n				minHeight : 500\r\n		});\r\n	});\r\n\r\nfunction selectSupplierAddress(supplierAddressJsonStr,echoParameter){\r\n	var supplierAddressBean = jQuery.parseJSON(supplierAddressJsonStr);\r\n	if(supplierAddressBean.addressId != \"\"){\r\n		if(echoParameter=='sourceInfo'){\r\n			$(\"#sourceInfoId\").val(supplierAddressBean.addressId);\r\n			$(\"#sourceInfoName\").val(supplierAddressBean.supplierName);\r\n		}else if (echoParameter=='destinationInfo'){\r\n			$(\"#destinationInfoId\").val(supplierAddressBean.addressId);\r\n			$(\"#destinationInfoName\").val(supplierAddressBean.supplierName);\r\n		}\r\n		\r\n	}\r\n}\r\nfunction selectWarehouse(warehouseJsonStr,echoParameter){\r\n	var warehouseJsonBean = jQuery.parseJSON(warehouseJsonStr);\r\n	if(warehouseJsonBean.warehouseId != \"\"){\r\n		if(echoParameter=='sourceInfo'){\r\n			$(\"#sourceInfoId\").val(warehouseJsonBean.warehouseId);\r\n			$(\"#sourceInfoName\").val(warehouseJsonBean.warehouseName);\r\n		}else if (echoParameter=='destinationInfo'){\r\n			$(\"#destinationInfoId\").val(warehouseJsonBean.warehouseId);\r\n			$(\"#destinationInfoName\").val(warehouseJsonBean.warehouseName);\r\n		}\r\n		\r\n	}\r\n}\r\n</script>\r\n</html>".toCharArray();
    _jsp_string30 = "'){\r\n				var url = \"".toCharArray();
    _jsp_string9 = "'; \r\n	</script>\r\n</head>\r\n<body class=\"article_bg\">\r\n	<p class=\"article_tit\">\u8def\u5f84\u4fe1\u606f</p>\r\n	<form id=\"formData\" name=\"formData\" method=\"post\" action=\"RouteInfoManage.do\" onsubmit=\"javascript:return checkForm('formData');\">\r\n	  <input type=\"hidden\" name=\"routeId\" id=\"routeId\" value=\"".toCharArray();
    _jsp_string16 = "\"  readOnly size=\"50\" checkStr=\"\u8d77\u70b9\u7ad9;txt;true;;200\"/>\r\n	      	<input type=\"hidden\" name=\"sourceInfoId\" id=\"sourceInfoId\" value=\"".toCharArray();
    _jsp_string6 = "/js/ui.js\"></script>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n	<title>\u8def\u5f84\u4fe1\u606f</title>\r\n	<script type=\"text/javascript\" src=\"../js/tms-common.js\"></script>\r\n	<script type='text/javascript' src=\"".toCharArray();
    _jsp_string19 = "\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\"><span>*</span>\u7ec8\u70b9\u4fe1\u606f\u7c7b\u578b\uff1a</em>    \r\n	      	<select  name=\"destinationInfoType\" id=\"destinationInfoType\" checkStr=\"\u7ec8\u70b9\u4fe1\u606f\u7c7b\u578b;txt;true;;50\">\r\n	      		".toCharArray();
    _jsp_string31 = "/srm/SupplierAddressEntitySelect.do?callbackFun=selectSupplierAddress&echoParameter=destinationInfo&addressId=\"+ destinationInfoId ;\r\n			}else if (destinationInfoType == '".toCharArray();
    _jsp_string17 = "\"/>\r\n	      	".toCharArray();
    _jsp_string1 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n	\r\n\r\n\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string27 = "'){\r\n			var url = \"".toCharArray();
    _jsp_string28 = "/srm/SupplierAddressEntitySelect.do?callbackFun=selectSupplierAddress&echoParameter=sourceInfo&addressId=\"+ sourceInfoId;\r\n		}else if (sourceInfoType == '".toCharArray();
    _jsp_string23 = "\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\">\u6709\u6548\u72b6\u6001\uff1a</em>\r\n	      <input type=\"checkbox\" name=\"status\" id=\"status\" value=\"".toCharArray();
    _jsp_string11 = "\" checkStr=\"\u8def\u5f84\u540d\u79f0;txt;true;;100\"/>\r\n	    </p>\r\n	    <p>\r\n	      <em class=\"int_label\"><span>*</span>\u8d77\u70b9\u4fe1\u606f\u7c7b\u578b\uff1a</em>    \r\n	      	<select  name=\"sourceInfoType\" id=\"sourceInfoType\" checkStr=\"\u8d77\u70b9\u4fe1\u606f\u7c7b\u578b;txt;true;;50\">\r\n	      		".toCharArray();
    _jsp_string2 = "\r\n<link href=\"".toCharArray();
    _jsp_string12 = "<option value=\"".toCharArray();
    _jsp_string24 = "/>\r\n	    </p>\r\n	    <p class=\"p_top_border\">\r\n	      <em class=\"int_label\">\u5907\u6ce8\uff1a</em>\r\n	      <textarea  name=\"memo\" id=\"memo\" cols=\"60\" rows=\"3\" checkStr=\"\u5907\u6ce8;txt;false;;1000\">".toCharArray();
    _jsp_string4 = "/js/jquery.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string8 = "/js/fancyBox/jquery.fancybox.css\" type=\"text/css\" media=\"screen\" />\r\n	<script type=\"text/javascript\">\r\n        document.domain='".toCharArray();
    _jsp_string18 = "\r\n	      	<input type=\"button\" name=\"selectSourceInfo\" id=\"selectSourceInfo\" value=\"\u6dfb\u52a0\" />\r\n	      	".toCharArray();
    _jsp_string14 = "</option>".toCharArray();
    _jsp_string26 = "';\r\n	if(readOnly=='true') {\r\n		disablePageElement();\r\n	}\r\n});\r\n$(\"#selectSourceInfo\").click(\r\n	function() {\r\n		var sourceInfoType = $(\"#sourceInfoType\").val();\r\n		var sourceInfoId = $(\"#sourceInfoId\").val();\r\n		if(sourceInfoType == '".toCharArray();
    _jsp_string29 = "/erp/WarehouseInfoSelect.do?callbackFun=selectWarehouse&echoParameter=sourceInfo&warehouseId=\"+ sourceInfoId;\r\n		}\r\n		$.fancybox.open({\r\n			href : url,\r\n			type : 'iframe',\r\n			width : 760,\r\n			minHeight : 500\r\n	});\r\n});\r\n\r\n$(\"#selectDestinationInfo\").click(\r\n		function() {\r\n			var destinationInfoType = $(\"#destinationInfoType\").val();\r\n			var destinationInfoId = $(\"#destinationInfoId\").val();\r\n			if(destinationInfoType == '".toCharArray();
  }
}
