// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `tms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.tms.component;

public interface TmsService extends Ice.Object,
                                    _TmsServiceOperations, _TmsServiceOperationsNC
{
    public static final String ice_staticId = "::com::lpmas::tms::component::TmsService";

    public static final long serialVersionUID = -1876894867L;
}
