/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._web_22dinf._pages._tms._waybill;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.lpmas.tms.waybill.busniess.WaybillStatusProcessor;
import java.util.*;
import com.lpmas.framework.config.*;
import com.lpmas.framework.bean.*;
import com.lpmas.framework.page.*;
import com.lpmas.framework.util.*;
import com.lpmas.framework.web.*;
import com.lpmas.admin.bean.*;
import com.lpmas.admin.business.*;
import com.lpmas.admin.config.*;
import com.lpmas.admin.client.cache.AdminUserInfoClientCache;
import com.lpmas.constant.info.InfoTypeConfig;
import com.lpmas.tms.waybill.bean.*;
import com.lpmas.tms.logistics.bean.*;
import com.lpmas.tms.waybill.config.*;
import com.lpmas.tms.config.*;

public class _waybillinfolist__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
AdminUserHelper adminHelper = (AdminUserHelper)request.getAttribute("AdminUserHelper");
List<WaybillEntityBean> list = (List<WaybillEntityBean>)request.getAttribute("WaybillEntityList");
List<LogisticsCompanyInfoBean> companyInfoList = (List<LogisticsCompanyInfoBean>) request.getAttribute("CompanyInfoList");
Map<Integer,String> routeInfoMap = (Map<Integer,String>) request.getAttribute("RouteInfoMap");
Map<Integer,String> CompanyInfoMap = (Map<Integer,String>) request.getAttribute("CompanyInfoMap");
List<Integer> waybillInfoCreaterUserList = (List<Integer>) request.getAttribute("WaybillInfoCreaterUserList");
int infoId = ParamKit.getIntParameter(request, "infoId", 0);
AdminUserInfoClientCache adminCache = new AdminUserInfoClientCache();
PageBean PAGE_BEAN = (PageBean)request.getAttribute("PageResult");
List<String[]> COND_LIST = (List<String[]>)request.getAttribute("CondList");

    out.write(_jsp_string1, 0, _jsp_string1.length);
    
String DOMAIN = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "DEFAULT_DOMAIN");
String STATIC_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "STATIC_URL");
String SRM_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "SRM_URL");
String ERP_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "ERP_URL");
String TMS_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "TMS_URL");
String REGION_URL = PropertiesKit.getBundleProperties(TmsConsoleConfig.TMS_PROP_FILE_NAME, "REGION_URL");

    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((STATIC_URL ));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((DOMAIN));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    int companyId = ParamKit.getIntParameter(request, "companyId", 0);
	for (LogisticsCompanyInfoBean logisticsCompanyInfoBean : companyInfoList) {
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((logisticsCompanyInfoBean.getCompanyId()));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((logisticsCompanyInfoBean.getCompanyId() == companyId ? "selected" : ""));
    out.write('>');
    out.print((logisticsCompanyInfoBean.getCompanyName()));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    }
    out.write(_jsp_string13, 0, _jsp_string13.length);
    int infoType = ParamKit.getIntParameter(request, "infoType", 0);
	for (StatusBean<Integer, String> statusBean :WaybillConfig.WAYBILL_INFO_TYPE_LIST) {
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((statusBean.getStatus()));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((statusBean.getStatus() == infoType ? "selected" : ""));
    out.write('>');
    out.print((statusBean.getValue()));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    }
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((ParamKit.getParameter(request, "infoNumber", "") ));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((infoId));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    
			int createUser = ParamKit.getIntParameter(request, "createUser", 0);
			for (Integer user : waybillInfoCreaterUserList) {
		
    out.write(_jsp_string17, 0, _jsp_string17.length);
    out.print((user));
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print(((user == createUser) ? "selected" : ""));
    out.write('>');
    out.print((adminCache.getAdminUserNameByKey(user)));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    
			}
		
    out.write(_jsp_string20, 0, _jsp_string20.length);
    
		String approvalStatus = ParamKit.getParameter(request, "approvalStatus", "");
		for (StatusBean<String, String> statusBean :WaybillConfig.REVIEW_STATUS_LIST) {
	
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((statusBean.getStatus()));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print(((statusBean.getStatus().equals(approvalStatus)) ? "selected" : ""));
    out.write('>');
    out.print((statusBean.getValue()));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    
		}
	
    out.write(_jsp_string22, 0, _jsp_string22.length);
    
		String waybillStatus = ParamKit.getParameter(request, "waybillStatus", "");
		for (StatusBean<String, String> statusBean :WaybillConfig.WAYBILL_STATUS_LIST) {
	
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((statusBean.getStatus()));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print(((statusBean.getStatus().equals(waybillStatus)) ? "selected" : ""));
    out.write('>');
    out.print((statusBean.getValue()));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    
		}
	
    out.write(_jsp_string23, 0, _jsp_string23.length);
    if(adminHelper.hasPermission(WaybillResource.WAYBILL_INFO, OperationConfig.CREATE)){ 
    out.write(_jsp_string24, 0, _jsp_string24.length);
    } 
    out.write(_jsp_string25, 0, _jsp_string25.length);
    
    WaybillStatusProcessor processor = null;
    for(WaybillEntityBean bean:list){ 
    	processor = new WaybillStatusProcessor(bean);
    
    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string27, 0, _jsp_string27.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string28, 0, _jsp_string28.length);
    out.print((bean.getWaybillId() ));
    out.write(_jsp_string29, 0, _jsp_string29.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string30, 0, _jsp_string30.length);
    out.print((bean.getWaybillNumber()));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((MapKit.getValueFromMap(bean.getLogisticsCompanyId(), CompanyInfoMap)));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((bean.getRouteName()));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((MapKit.getValueFromMap(bean.getInfoType(), WaybillConfig.WAYBILL_INFO_TYPE_MAP)));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((bean.getWareNumber()));
    out.write(_jsp_string32, 0, _jsp_string32.length);
    out.print((bean.getTotalAmount()));
    out.write(_jsp_string33, 0, _jsp_string33.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string30, 0, _jsp_string30.length);
    out.print((MapKit.getValueFromMap(bean.getApprovalStatus(), WaybillConfig.REVIEW_STATUS_MAP)));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((MapKit.getValueFromMap(bean.getWaybillStatus(), WaybillConfig.WAYBILL_STATUS_MAP)));
    out.write(_jsp_string34, 0, _jsp_string34.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string35, 0, _jsp_string35.length);
    if(adminHelper.hasPermission(WaybillResource.WAYBILL_INFO, OperationConfig.UPDATE)&& !processor.isLock()){ 
    out.write(_jsp_string36, 0, _jsp_string36.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string37, 0, _jsp_string37.length);
    } 
    out.write(_jsp_string38, 0, _jsp_string38.length);
    if(adminHelper.hasPermission(WaybillResource.WAYBILL_INFO, OperationConfig.UPDATE)&& processor.committable()){ 
    out.write(_jsp_string39, 0, _jsp_string39.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string40, 0, _jsp_string40.length);
    out.print((WaybillConfig.WAYBILL_ACTION_COMMIT));
    out.write(_jsp_string41, 0, _jsp_string41.length);
    } 
    out.write(_jsp_string38, 0, _jsp_string38.length);
    if(adminHelper.hasPermission(WaybillResource.WAYBILL_INFO, OperationConfig.UPDATE)&& processor.cancelCommittable()){ 
    out.write(_jsp_string39, 0, _jsp_string39.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string40, 0, _jsp_string40.length);
    out.print((WaybillConfig.WAYBILL_ACTION_CANCEL_COMMIT));
    out.write(_jsp_string42, 0, _jsp_string42.length);
    } 
    out.write(_jsp_string38, 0, _jsp_string38.length);
    if(adminHelper.hasPermission(WaybillResource.WAYBILL_INFO, OperationConfig.UPDATE)&& processor.placeOrderable()){ 
    out.write(_jsp_string39, 0, _jsp_string39.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string40, 0, _jsp_string40.length);
    out.print((WaybillConfig.WAYBILL_ACTION_PLACE_ORDER));
    out.write(_jsp_string43, 0, _jsp_string43.length);
    } 
    out.write(_jsp_string38, 0, _jsp_string38.length);
    if(adminHelper.hasPermission(WaybillResource.WAYBILL_INFO, OperationConfig.UPDATE)&& processor.receiveable()){ 
    out.write(_jsp_string39, 0, _jsp_string39.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string40, 0, _jsp_string40.length);
    out.print((WaybillConfig.WAYBILL_ACTION_REVEICE));
    out.write(_jsp_string44, 0, _jsp_string44.length);
    } 
    out.write(_jsp_string38, 0, _jsp_string38.length);
    if(adminHelper.hasPermission(WaybillResource.WAYBILL_INFO, OperationConfig.UPDATE)&& processor.closable()){ 
    out.write(_jsp_string39, 0, _jsp_string39.length);
    out.print((bean.getWaybillId()));
    out.write(_jsp_string40, 0, _jsp_string40.length);
    out.print((WaybillConfig.WAYBILL_ACTION_CLOSE));
    out.write(_jsp_string45, 0, _jsp_string45.length);
    } 
    out.write(_jsp_string46, 0, _jsp_string46.length);
    } 
    out.write(_jsp_string47, 0, _jsp_string47.length);
    if(adminHelper.hasPermission(WaybillResource.WAYBILL_INFO, OperationConfig.CREATE)){ 
    out.write(_jsp_string48, 0, _jsp_string48.length);
    } 
    out.write(_jsp_string49, 0, _jsp_string49.length);
    if (adminHelper.hasPermission(WaybillResource.WAYBILL_INFO,OperationConfig.REMOVE)) {
    out.write(_jsp_string50, 0, _jsp_string50.length);
    }
    out.write(_jsp_string51, 0, _jsp_string51.length);
    if (adminHelper.hasPermission(WaybillResource.WAYBILL_INFO,OperationConfig.APPROVE)) {
    out.write(_jsp_string52, 0, _jsp_string52.length);
    }
    out.write(_jsp_string53, 0, _jsp_string53.length);
    for(String[] condArray :COND_LIST){ 
    out.write(_jsp_string54, 0, _jsp_string54.length);
    out.print((condArray[0] ));
    out.write(_jsp_string55, 0, _jsp_string55.length);
    out.print((condArray[0] ));
    out.write(_jsp_string27, 0, _jsp_string27.length);
    out.print((condArray[1] ));
    out.write(_jsp_string56, 0, _jsp_string56.length);
    } 
    out.write(_jsp_string57, 0, _jsp_string57.length);
    if(PAGE_BEAN.getCurrentPageNumber()>1){ 
    out.write(_jsp_string58, 0, _jsp_string58.length);
    out.print((PAGE_BEAN.getPrePageNumber() ));
    out.write(_jsp_string59, 0, _jsp_string59.length);
    } 
    out.write(_jsp_string60, 0, _jsp_string60.length);
    out.print((PAGE_BEAN.getTotalRecordNumber() ));
    out.write(_jsp_string61, 0, _jsp_string61.length);
    out.print((PAGE_BEAN.getPageSize() ));
    out.write(_jsp_string62, 0, _jsp_string62.length);
    out.print((PAGE_BEAN.getCurrentPageNumber() ));
    out.write(_jsp_string63, 0, _jsp_string63.length);
    out.print((PAGE_BEAN.getTotalPageNumber() ));
    out.write(_jsp_string64, 0, _jsp_string64.length);
    if(PAGE_BEAN.getCurrentPageNumber() < PAGE_BEAN.getTotalPageNumber()){ 
    out.write(_jsp_string65, 0, _jsp_string65.length);
    out.print((PAGE_BEAN.getNextPageNumber() ));
    out.write(_jsp_string66, 0, _jsp_string66.length);
    out.print((PAGE_BEAN.getTotalPageNumber() ));
    out.write(_jsp_string67, 0, _jsp_string67.length);
    } 
    out.write(_jsp_string68, 0, _jsp_string68.length);
    out.print((PAGE_BEAN.getTotalPageNumber() ));
    out.write(_jsp_string69, 0, _jsp_string69.length);
    out.print((InfoTypeConfig.INFO_TYPE_WAREHOUSE_TRANSFER_ORDER));
    out.write(_jsp_string70, 0, _jsp_string70.length);
    out.print((ERP_URL));
    out.write(_jsp_string71, 0, _jsp_string71.length);
    out.print((WaybillConfig.REVIEW_STATUS_MAP.get(WaybillConfig.REVIEW_STATUS_WAIT_APPROVE)));
    out.write(_jsp_string72, 0, _jsp_string72.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/tms/waybill/WaybillInfoList.jsp"), -9172474308316115711L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/include/header.jsp"), -5467580586608798099L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/include/page.jsp"), -7400274417948715423L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string35;
  private final static char []_jsp_string40;
  private final static char []_jsp_string67;
  private final static char []_jsp_string70;
  private final static char []_jsp_string49;
  private final static char []_jsp_string61;
  private final static char []_jsp_string47;
  private final static char []_jsp_string3;
  private final static char []_jsp_string17;
  private final static char []_jsp_string32;
  private final static char []_jsp_string44;
  private final static char []_jsp_string11;
  private final static char []_jsp_string5;
  private final static char []_jsp_string58;
  private final static char []_jsp_string24;
  private final static char []_jsp_string22;
  private final static char []_jsp_string30;
  private final static char []_jsp_string31;
  private final static char []_jsp_string6;
  private final static char []_jsp_string66;
  private final static char []_jsp_string62;
  private final static char []_jsp_string52;
  private final static char []_jsp_string72;
  private final static char []_jsp_string53;
  private final static char []_jsp_string21;
  private final static char []_jsp_string28;
  private final static char []_jsp_string7;
  private final static char []_jsp_string26;
  private final static char []_jsp_string15;
  private final static char []_jsp_string12;
  private final static char []_jsp_string27;
  private final static char []_jsp_string71;
  private final static char []_jsp_string16;
  private final static char []_jsp_string57;
  private final static char []_jsp_string69;
  private final static char []_jsp_string50;
  private final static char []_jsp_string54;
  private final static char []_jsp_string20;
  private final static char []_jsp_string13;
  private final static char []_jsp_string36;
  private final static char []_jsp_string39;
  private final static char []_jsp_string42;
  private final static char []_jsp_string68;
  private final static char []_jsp_string29;
  private final static char []_jsp_string55;
  private final static char []_jsp_string37;
  private final static char []_jsp_string23;
  private final static char []_jsp_string64;
  private final static char []_jsp_string2;
  private final static char []_jsp_string63;
  private final static char []_jsp_string18;
  private final static char []_jsp_string46;
  private final static char []_jsp_string4;
  private final static char []_jsp_string65;
  private final static char []_jsp_string33;
  private final static char []_jsp_string56;
  private final static char []_jsp_string34;
  private final static char []_jsp_string51;
  private final static char []_jsp_string9;
  private final static char []_jsp_string48;
  private final static char []_jsp_string43;
  private final static char []_jsp_string19;
  private final static char []_jsp_string10;
  private final static char []_jsp_string59;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string41;
  private final static char []_jsp_string60;
  private final static char []_jsp_string38;
  private final static char []_jsp_string8;
  private final static char []_jsp_string45;
  private final static char []_jsp_string14;
  private final static char []_jsp_string25;
  static {
    _jsp_string35 = "&readOnly=true\">\u67e5\u770b</a> \r\n      ".toCharArray();
    _jsp_string40 = "&statusAction=".toCharArray();
    _jsp_string67 = ");\">&nbsp;</em>".toCharArray();
    _jsp_string70 = "'){\r\n						url = \"/erp/WarehouseTransferOrderInfoSelect.do\";\r\n						selectfunction = \"selectWarehouseTransfer\";\r\n					}else{\r\n						url = \"/erp/DeliveryNoteInfoSelect.do\";\r\n						selectfunction = \"selectDeliveryNote\";\r\n					}\r\n				}\r\n				$.fancybox.open({\r\n					href : '".toCharArray();
    _jsp_string49 = "\r\n ".toCharArray();
    _jsp_string61 = "</b>\u6761  \u6bcf\u9875\u663e\u793a<b>".toCharArray();
    _jsp_string47 = "\r\n  </table>\r\n</form>\r\n<ul class=\"page_info\">\r\n<li class=\"page_left_btn\">\r\n".toCharArray();
    _jsp_string3 = "/css/main.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string17 = "\r\n		<option value=\"".toCharArray();
    _jsp_string32 = "</td>\r\n      <td align=\"right\">".toCharArray();
    _jsp_string44 = "\">\u6536\u8d27</a>".toCharArray();
    _jsp_string11 = "\" ".toCharArray();
    _jsp_string5 = "/js/common.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string58 = "<em class=\"first\" onclick=\"javascript:goPage('formPage',1);\">&nbsp;</em>\r\n  <em class=\"pre\" onclick=\"javascript:goPage('formPage',".toCharArray();
    _jsp_string24 = "\r\n    <input type=\"button\" name=\"button\" id=\"button\" class=\"search_btn_sub\" value=\"\u65b0\u5efa\" onclick=\"javascript:location.href='/waybill/WaybillInfoManage.do'\">\r\n    ".toCharArray();
    _jsp_string22 = "\r\n	</select>\r\n	<em class=\"em1\">\u8fdb\u5ea6\uff1a</em> \r\n	<select name=\"waybillStatus\" id=\"waybillStatus\">\r\n	<option value=\"\"></option>\r\n	".toCharArray();
    _jsp_string30 = "\">".toCharArray();
    _jsp_string31 = "</td>\r\n      <td>".toCharArray();
    _jsp_string6 = "/js/ui.js\"></script>\r\n<script type='text/javascript' src=\"".toCharArray();
    _jsp_string66 = ");\">&nbsp;</em>\r\n  <em class=\"last\" onclick=\"javascript:goPage('formPage',".toCharArray();
    _jsp_string62 = "</b>\u6761 \u5f53\u524d\u7b2c<b>".toCharArray();
    _jsp_string52 = "\r\n	<input type=\"button\" name=\"review\" id=\"review\" disabled=\"disabled\" value=\"\u5ba1\u6279\"> \r\n".toCharArray();
    _jsp_string72 = "\";\r\n	if(reviewStatus == waitApprove ){				\r\n		$('#review').removeAttr(\"disabled\"); \r\n	}else{\r\n	   $('#review').attr(\"disabled\",\"disabled\"); \r\n	}\r\n}\r\nfunction selectReviewResult(result){\r\n	var waybillId = $('input:radio[name=waybillId]:checked').val();		\r\n	var url = \"WaybillStatusManage.do?waybillId=\"+ waybillId +\"&statusAction=\"+ result;\r\n	window.location.href= url\r\n}\r\n</script>\r\n</html>".toCharArray();
    _jsp_string53 = "\r\n</li>\r\n\r\n<form name=\"formPage\" method=\"post\" action=\"\">\r\n<input type=\"hidden\" name=\"pageNum\" id=\"pageNum\" value=\"\"/>\r\n".toCharArray();
    _jsp_string21 = "\"\r\n		".toCharArray();
    _jsp_string28 = "\" onclick=\"changeDisable()\"></td>\r\n      <td>".toCharArray();
    _jsp_string7 = "/js/fancyBox/jquery.fancybox.js\"></script>\r\n<link rel=\"stylesheet\" href=\"".toCharArray();
    _jsp_string26 = "\r\n    <tr>\r\n      <td><input type=\"radio\" name=\"waybillId\" id=\"radio_".toCharArray();
    _jsp_string15 = "\" size=\"20\" id=\"selectInfo\" readonly/>\r\n	<input type=\"hidden\" name=\"infoId\" id=\"infoId\" value=\"".toCharArray();
    _jsp_string12 = "</option>\r\n	".toCharArray();
    _jsp_string27 = "\" value=\"".toCharArray();
    _jsp_string71 = "'+url+'?callbackFun='+selectfunction,\r\n					type : 'iframe',\r\n					width : 560,\r\n					minHeight : 150\r\n			});\r\n		});\r\n});\r\nfunction selectWarehouseTransfer(transferOrderJsonStr, sourceWarehouseJsonStr,targetWarehouseJsonStr){\r\n	var warehouseTransferOrderInfoBean = jQuery.parseJSON(transferOrderJsonStr);\r\n	if(warehouseTransferOrderInfoBean.toId != \"\" && warehouseTransferOrderInfoBean.toNumber != \"\"){		\r\n		$(\"#infoId\").val(warehouseTransferOrderInfoBean.toId);\r\n		$(\"#selectInfo\").val(warehouseTransferOrderInfoBean.toNumber);\r\n	}\r\n}\r\nfunction selectDeliveryNote(deliveryNoteJsonStr, purchaseOrderJsonStr){\r\n	var deliveryNoteInfoBean = jQuery.parseJSON(deliveryNoteJsonStr);\r\n	if(deliveryNoteInfoBean.dnId != \"\" && deliveryNoteInfoBean.dnNumber != \"\"){		\r\n		$(\"#infoId\").val(deliveryNoteInfoBean.dnId);\r\n		$(\"#selectInfo\").val(deliveryNoteInfoBean.dnNumber);\r\n	}\r\n}\r\nfunction changeDisable(){\r\n	var waybillId = $('input:radio[name=waybillId]:checked').val();\r\n	var reviewStatus = $(\"#reviewStatus_\"+waybillId).html();\r\n	var waitApprove = \"".toCharArray();
    _jsp_string16 = "\"/> \r\n	<em class=\"em1\">\u521b\u5efa\u4eba:</em> \r\n	<select name=\"createUser\" id=\"createUser\">\r\n		<option value=\"\"></option>\r\n		".toCharArray();
    _jsp_string57 = "\r\n</form>\r\n<li class=\"page_num\">\r\n  ".toCharArray();
    _jsp_string69 = ");\"/> \r\n</li>\r\n</ul>\r\n</body>\r\n<script>\r\n$(document).ready(function() {\r\n	$(\"#delete\").click(function() {\r\n		var waybillId = $('input:radio[name=waybillId]:checked').val();	\r\n		if (typeof(waybillId) == \"undefined\"){\r\n		    alert(\"\u8bf7\u9009\u62e9\u9700\u8981\u5220\u9664\u7684\u627f\u8fd0\u5355\");\r\n		    return;\r\n		}\r\n		var waybillNumber = $('#waybillNumber_'+waybillId).html();\r\n		if(confirm(\"\u786e\u5b9a\u8981\u5220\u9664\u627f\u8fd0\u5355\"+waybillNumber+\"\u5417?\")){\r\n			var url = \"WaybillInfoRemove.do?waybillId=\"+ waybillId ;\r\n			window.location.href= url\r\n		 }\r\n		\r\n	});	\r\n	$(\"#review\").click(function() {\r\n		var waybillId = $('input:radio[name=waybillId]:checked').val();			\r\n		$.fancybox.open({\r\n			href : 'WaybillApproveResultSelect.do?callbackFun=selectReviewResult&waybillId=' + waybillId,\r\n			type : 'iframe',\r\n			width : 560,\r\n			minHeight : 150\r\n		});		\r\n	});\r\n	$(\"#selectInfo\").click(\r\n			function() {				\r\n				var url = \"\";\r\n				var selectfunction = \"\";\r\n				var infoType = $('#infoType').val().trim();\r\n				if(infoType==\"\"){\r\n					alert(\"\u8bf7\u5148\u9009\u62e9\u8ba2\u5355\u7c7b\u578b\");\r\n					return;\r\n				}else{\r\n					if(infoType=='".toCharArray();
    _jsp_string50 = "\r\n	<input type=\"button\" name=\"delete\" id=\"delete\" value=\"\u5220\u9664\"> \r\n ".toCharArray();
    _jsp_string54 = "\r\n<input type=\"hidden\" name=\"".toCharArray();
    _jsp_string20 = "\r\n	</select>\r\n	<em class=\"em1\">\u5ba1\u6279\u72b6\u6001\uff1a</em> \r\n	<select name=\"approvalStatus\" id=\"approvalStatus\">\r\n	<option value=\"\"></option>\r\n	".toCharArray();
    _jsp_string13 = "</select>\r\n	<em class=\"em1\">\u5173\u8054\u8ba2\u5355\u7c7b\u578b\uff1a</em>\r\n    <select name=\"infoType\" id=\"infoType\">\r\n    <option value=\"\"></option>\r\n	".toCharArray();
    _jsp_string36 = "|<a href=\"/waybill/WaybillInfoManage.do?waybillId=".toCharArray();
    _jsp_string39 = "|<a href=\"/waybill/WaybillStatusManage.do?waybillId=".toCharArray();
    _jsp_string42 = "\">\u53d6\u6d88\u5ba1\u6279</a>".toCharArray();
    _jsp_string68 = "\r\n  <input name=\"goPageNum\" id=\"goPageNum\" type=\"text\" class=\"page_int_txt\"/><input name=\"\" type=\"button\" class=\"page_btn_go\" value=\"GO\" onclick=\"javascript:goInputPage('formPage',".toCharArray();
    _jsp_string29 = "</td>\r\n      <td id=\"waybillNumber_".toCharArray();
    _jsp_string55 = "\" id=\"".toCharArray();
    _jsp_string37 = "&readOnly=false\">\u4fee\u6539</a>".toCharArray();
    _jsp_string23 = "\r\n	</select>\r\n    <input name=\"\" type=\"submit\" class=\"search_btn_sub\" value=\"\u67e5\u8be2\"/>\r\n    ".toCharArray();
    _jsp_string64 = "\u9875 \r\n  ".toCharArray();
    _jsp_string2 = "\r\n<link href=\"".toCharArray();
    _jsp_string63 = "</b>/".toCharArray();
    _jsp_string18 = "\"\r\n			".toCharArray();
    _jsp_string46 = "\r\n      </td>\r\n    </tr>\r\n    ".toCharArray();
    _jsp_string4 = "/js/jquery.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string65 = "<em class=\"next\" onclick=\"javascript:goPage('formPage',".toCharArray();
    _jsp_string33 = "</td>\r\n      <td id=\"reviewStatus_".toCharArray();
    _jsp_string56 = "\"/>".toCharArray();
    _jsp_string34 = "</td>\r\n      <td align=\"center\">\r\n      <a href=\"/waybill/WaybillInfoManage.do?waybillId=".toCharArray();
    _jsp_string51 = "\r\n".toCharArray();
    _jsp_string9 = "'; \r\n</script>\r\n</head>\r\n<body class=\"article_bg\">\r\n<p class=\"article_tit\">\u627f\u8fd0\u5355</p>\r\n<form name=\"formSearch\" method=\"post\" action=\"/waybill/WaybillInfoList.do\">\r\n  <div class=\"search_form\">\r\n    <em class=\"em1\">\u7269\u6d41\u516c\u53f8\uff1a</em>\r\n    <select name=\"companyId\" id=\"companyId\">\r\n    <option value=\"\"></option>\r\n	".toCharArray();
    _jsp_string48 = "\r\n  <input type=\"button\" name=\"button\" id=\"button\" value=\"\u65b0\u5efa\" onclick=\"javascript:location.href='/waybill/WaybillInfoManage.do'\">\r\n".toCharArray();
    _jsp_string43 = "\">\u4e0b\u5355</a>".toCharArray();
    _jsp_string19 = "\r\n		</option>\r\n		".toCharArray();
    _jsp_string10 = "\r\n	<option value=\"".toCharArray();
    _jsp_string59 = ");\"> &nbsp;</em>".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n<title>\u627f\u8fd0\u5355</title>\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string41 = "\">\u63d0\u4ea4\u5ba1\u6279</a>".toCharArray();
    _jsp_string60 = "\r\n       \u603b\u8bb0\u5f55<b>".toCharArray();
    _jsp_string38 = "\r\n      ".toCharArray();
    _jsp_string8 = "/js/fancyBox/jquery.fancybox.css\" type=\"text/css\" media=\"screen\" />\r\n<script type=\"text/javascript\">\r\n        document.domain='".toCharArray();
    _jsp_string45 = "\">\u5173\u95ed</a>".toCharArray();
    _jsp_string14 = "</select>\r\n	<em class=\"em1\">\u5173\u8054\u8ba2\u5355\u53f7\uff1a</em> \r\n	<input type=\"text\" name=\"infoNumber\" value=\"".toCharArray();
    _jsp_string25 = "\r\n  </div>\r\n  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"table_style\">\r\n    <tr>\r\n      <th>\u9009\u62e9</th>\r\n      <th>\u627f\u8fd0\u5355ID</th>\r\n      <th>\u627f\u8fd0\u5355\u7f16\u53f7</th>\r\n      <th>\u7269\u6d41\u516c\u53f8</th>\r\n      <th>\u7269\u6d41\u8def\u5f84</th>\r\n      <th>\u5173\u8054\u8ba2\u5355\u7c7b\u578b</th>\r\n      <th>\u5173\u8054\u8ba2\u5355\u53f7</th>\r\n      <th>\u603b\u8fd0\u8d39</th>\r\n      <th>\u5ba1\u6279\u72b6\u6001</th>\r\n      <th>\u8fdb\u5ea6\u72b6\u6001</th>\r\n      <th>\u64cd\u4f5c</th>\r\n    </tr>\r\n    ".toCharArray();
  }
}
